# Generated by Django 4.0.5 on 2022-07-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gato',
            old_name='Apodo',
            new_name='apodo',
        ),
    ]
